version: '3'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test_db
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - '27018:27017'

volumes:
  mongo-data:
