openapi: 3.0.0
info:
  title: API Buildings Administration
  description: API for Buildings Administration CABILDO
  version: 1.0.0
  contact:
    name: Codexar
    email: codexar.latam@gmail.com
servers:
  - url: "http://localhost:4000/api"
    description: Local Server
  - url: "https://api-buildings-administration.onrender.com/api"
    description: Production Server

# Import paths from modular files
paths:
  $ref: 'user.yaml#/paths'
  $ref: 'administration.yaml#/paths'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []