export const strings = {
  accept: 'Aceptar',
  cabildo: 'Cabildo',
  cancel: 'Cancelar',
  clickHere: 'Hacé click acá',
  dontHaveUser: '¿No tenés usuario?',
  forgotPassword: 'Olvidé mi clave',
  presentationText: `Cabildo es una aplicación web que facilita las transacciones entre la
  Administración de Consorcios y los habitantes de las unidades funcionales
  de un edificio. A través de Cabildo podrán gestionarse resúmenes de
  expensas, recibos de pagos, anuncios, reclamos, solicitudes y gastos del
  consorcio, entre otras funcionalidades.`,
  welcome: 'Bienvenido a Cabildo',
  nameAndSurname: 'Nombre y Apellido',
  validateMail: 'Por favor, ingrese un email válido',
  notMatchingPasswords: 'Las contraseñas no coinciden',
  user: 'Usuario',
  mail: 'Mail',
  password: 'Contraseña',
  confirmPassword: 'Confirmar contraseña',
  remainingCharacters: 'caracteres restantes',
  login: 'Iniciar Sesión',
  register: 'Regístrate aquí',
  logout: 'Cerrar Sesión',
  setBuilding: 'Configurar Edificio',
  street: 'Calle',
  number: 'Número',
  floors: 'Pisos',
  premise: 'Local',
  letters: 'Letras',
  numbers: 'Números',
  groundFloor: 'Planta Baja',
  duplicateTower: 'Duplicar Torre',
  addTower: 'Agregar Torre',
  plan: 'Plan',
  enterStreet: 'Ingrese la Calle',
  enterNumber: 'Ingrese el Número',
  tower: 'Torre',
  planDetails: 'El plan se completará automáticamente luego de seleccionar las UF',
  sameFloors: 'Pisos Iguales',
  floor: 'Piso',
  removeTower: 'Eliminar Torre',
  functionalUnitsNumber: 'Ingrese número de unidades funcionales'
}
